# Generated by Django 5.0.3 on 2024-03-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_news_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
