# Generated by Django 5.0.3 on 2024-03-09 22:24

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to=myapp.models.news_image_path),
        ),
    ]
